### ISSUE TITLE
Be honest .. is this dead in the water?

### ISSUE THREAD

**Issue by pm64** [gaelj/BlazorCodeMirror6#10]
I've been so excited about this project ever since it landed on my radar, but I wonder about its future? In fairness, it's barely an infant. But I'd LOVE to use this -- seems the author ran into a problem running multiple instances on same page,  bug is still open. I wish I could be more helpful with this stuff. Any chance of a revival?

**Comment by gaelj** [comment]
Hey @pm64, thanks for your interest in this project. I've found some time to fix the known issues and implement some new features. Many more to come, if you need some specific feature, please let me know.

**Comment by pm64** [comment]
Thanks @gaelj, was very happy to see the recent updates pouring in. Welcome back!
