### ISSUE TITLE
Note of appreciation

### ISSUE THREAD

**Issue by pm64** [gaelj/BlazorCodeMirror6#18]
Sorry to open this issue @gaelj, I couldn't find another way to communicate with you.

Just wanted to congratulate you on the recent updates and express my sincerest appreciation for sharing this project.

I would love to see a Discussions section in this repo, or perhaps a Gitter channel, as a way to discuss this component with other users.. maybe something to think about.

In any case, thanks again for this beautiful work!

**Comment by gaelj** [comment]
Hi & thanks, I've created a discussion section.

**Comment by pm64** [comment]
Fantastic! Will be interested to see if it gets any use. Nice option to have either way.

**Comment by StefH** [comment]
@gaelj 
Thank you for implementing this project !
