### ISSUE TITLE
Remove Focus On Load?

### ISSUE THREAD

**Issue by YodasMyDad** [gaelj/BlazorCodeMirror6#184]
This is really cool. Great work. Only annoying thing is, when the editor loads on the page, it makes the page jump down to the editor? Anyway to stop the auto focus on load? So the user can scroll down the page to the editor when they are ready?

**Comment by gaelj** [comment]
Is `FocusOnCreation` set to `false` ?

https://github.com/gaelj/BlazorCodeMirror6/blob/8cd15692db3752f1e74fecb73163c1e13312ef04/CodeMirror6/Models/CodeMirrorSetup.cs#L117

**Comment by YodasMyDad** [comment]
Yes, this is what I'm doing

```
<CodeMirror6Wrapper
    @ref="@CodeMirror6WrapperRef"
    IsWASM="@(false)"
    @bind-Doc="@Code"
    Language="@Language"
    Editable="@(true)"
    LineNumbers="@(true)"
    LineWrapping="@(false)"
    Theme="ThemeMirrorTheme.Copilot"
    Setup="@_setup"
    MaxHeight="25rem"
    >
</CodeMirror6Wrapper>
```
and my setup is

```
    private readonly CodeMirrorSetup _setup = new() {
        FocusOnCreation = false
    };
```

**Comment by gaelj** [comment]
`FocusOnCreation` was a false lead I gave from the top of my head. There was indeed a bug. The old behaviour is now optionally triggered by the new `ScrollToStart` setup parameter.

**Comment by YodasMyDad** [comment]
Great thanks, will update
