### ISSUE TITLE
Connection lost - file size limit?

### ISSUE THREAD

**Issue by wilhelmberg** [gaelj/BlazorCodeMirror6#192]
First and foremost, thank you for creating this component.

I was wondering if there is a hard (or configurable) limit to the size of the files that can be loaded - either in your component or Blazor in general?

I have an `InteractiveServer` project that I need to load various JSON files with.
'Crashes' (`Attempting to reconnect to the server`) happen consistently in my app and in your examples when the files get too big.

See the attached video.

The limit seems to be around 30KB:
✅ file with 30_098 bytes
❌ file with 30_965 bytes

I also tried the different demos:
❌ Examples.BlazorServer
❌ Examples.BlazorServerInteractive
✅  Examples.BlazorWasm

Unfortunately switching to Wasm is not possible for my project

The server connection seems to be badly damaged as subsequent clicks on the buttons again result in `Attempting to reconnect to the server`.

VS Console doesn't show any errors except the CSS error that can also be seen in the browser console:

```
warn: Microsoft.AspNetCore.Components.Web.ErrorBoundary[100]
      Unhandled exception rendering component: Failed to load CSS: _content/GaelJ.BlazorCodeMirror6/GaelJ.BlazorCodeMirror6.bundle.scp.css?v=1729934724085
Error: Failed to load CSS: _content/GaelJ.BlazorCodeMirror6/GaelJ.BlazorCodeMirror6.bundle.scp.css?v=1729934724085
    at link.onerror (https://localhost:7258/_content/GaelJ.BlazorCodeMirror6/index-Cb-nKWOX.js:77299:37)
      Microsoft.JSInterop.JSException: Failed to load CSS: _content/GaelJ.BlazorCodeMirror6/GaelJ.BlazorCodeMirror6.bundle.scp.css?v=1729934724085
Error: Failed to load CSS: _content/GaelJ.BlazorCodeMirror6/GaelJ.BlazorCodeMirror6.bundle.scp.css?v=1729934724085
    at link.onerror (https://localhost:7258/_content/GaelJ.BlazorCodeMirror6/index-Cb-nKWOX.js:77299:37)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at GaelJ.BlazorCodeMirror6.CodeMirror6WrapperInternal.CodeMirrorJsInterop.ModuleInvokeVoidAsync(String method, Object[] args) in C:\PathTo\BlazorCodeMirror6\CodeMirror6\CodeMirror6WrapperInternal.razor.JsInterop.cs:line 43
```

Any feedback on this problem is highly appreciated.
Let me know if you need more information.

![image](https://github.com/user-attachments/assets/2acae3e4-e93a-4432-807c-4e8405531208)

https://github.com/user-attachments/assets/76c8feef-1518-407c-8408-42e05276dfc7

**Comment by gaelj** [comment]
Yes, it's a known issue with the way Blazor server works. Basically in Blazor server your app in running on a server and updates get sent to the browser via a SignalR (aka websocket) connection. This connection has a buffer of fixed size.

When a file gets uploaded, it first gets written to the buffer to be sent to the front-end server via that SignalR connection. So if the file is too big, it exceeds the buffer size and an app crash is triggered.

The dirty workaround is to increase Blazor's buffer size with (in `Program.cs`) 

```cs
const int MAX_RECEIVE_SIZE = 102400000; // for example

builder.Services.AddServerSideBlazor().AddHubOptions(x => x.MaximumReceiveMessageSize = MAX_RECEIVE_SIZE);
```

You should still enforce a maximum attachment size on the UI side.

Be careful that increasing the Blazor buffer size makes Denial Of Service attacks easier to perform on your app. Only do this in production if your app in not exposed to the public internet !

A safer approach would be to handle file uploads with a specific API endpoint on the server side, and javascript code on the browser side that streams the file contents directly to the endpoint, without involving Blazor. I remember coming across some libraries for this...

MS docs: https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0

**Comment by wilhelmberg** [comment]
@gaelj  Thanks for your speedy response and explanations 🙏 

Setting `MaximumReceiveMessageSize` to a higher value fixes the problem and is good enough for my use case.
