### ISSUE TITLE
Support text/plain mode?

### ISSUE THREAD

**Issue by Gaz83** [gaelj/BlazorCodeMirror6#58]
Any chance to support text/plain mode?

**Comment by gaelj** [comment]
In the demo you can view the raw test by unchecking this box
![image](https://github.com/gaelj/BlazorCodeMirror6/assets/8884632/88ee87f1-e65d-492b-8b2f-b5732f4b5044)

This sets the component's `AutoFormatMarkdown` parameter accordingly.

If that's not what you have in mind, could you elaborate ?

**Comment by gaelj** [comment]
OK I think I understood : you want plain text as a language option ?

**Comment by Gaz83** [comment]
Yeah if possible. In CodeMirror5  you can set the mode to null or plain/text

Looking at what you wrote I am now thinking so set language to Markdown, switch off the autoformat and disable highlighting. This should do the same thing?
If so, wonder if you change so that you can select plain text and it sets those options for you.

**Comment by gaelj** [comment]
Implemented and deployed ; can you check and either close this issue or comment it ?

**Comment by Gaz83** [comment]
Got the following exception

`index-C6LAOLAl.js:77011  
Error in initializing CodeMirror TypeError: Cannot read properties of null (reading 'extension')
    at inner (index-C6LAOLAl.js:2038:31)
    at inner (index-C6LAOLAl.js:2022:13)
    at inner (index-C6LAOLAl.js:2015:17)
    at flatten (index-C6LAOLAl.js:2044:5)
    at Configuration.resolve (index-C6LAOLAl.js:1952:25)
    at EditorState.create (index-C6LAOLAl.js:2783:43)
    at Module.initCodeMirror (index-C6LAOLAl.js:76986:45)`

**Comment by gaelj** [comment]
Can you make sure the browser cache is cleaned ?

**Comment by Gaz83** [comment]
Just tried again with cache cleared, still the same.

**Comment by gaelj** [comment]
Are you running the example locally or are you on the [github actions demo](https://gaelj.github.io/BlazorCodeMirror6/) ? 

If locally, try running `dotnet clean` and `dotnet build` in the `CodeMirror6` project .

**Comment by Gaz83** [comment]
I am running it all locally. Cloned the git, referenced the project and using in my own projects. I am now going to use your examples project locally. Will get back in a few moments

**Comment by Gaz83** [comment]
Ok I have managed to replicate the issue locally in your examples.
Go into Example.razor and change the `Language` from the default `CodeMirrorLanguage.Markdown` to `CodeMirrorLanguage.PlainText` so that it starts up with that language set. Now when I run it I get the same errors.

**Comment by Gaz83** [comment]
I also just done this in my own project to confirm it's the initial setting. This works.

`protected override Task OnAfterRenderAsync(bool firstRender)
{
    if (_codeMirror is not null)
        if (_codeMirror.Language != CodeMirrorLanguage.PlainText)
                _codeMirror.Language = CodeMirrorLanguage.PlainText;

    return base.OnAfterRenderAsync(firstRender);
} `

**Comment by Gaz83** [comment]
I can confirm the issue is resolved. Tested and now using the nuget package :-D

**Comment by Gaz83** [comment]
I can confirm the issue is resolved. Tested and now using the nuget package :-D
