### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kampilan** [gaelj/BlazorCodeMirror6#6]
You project looks very interesting. While I support a creator's right to license their work as they see fit, your choice of GPL seems counter-productive and an adoption killer. You have built a GPL wrapper around a project that is licensed as MIT!?!?

GPL is a hard no for me, but good luck going forward.

Thanks
Jim

**Comment by pm64** [comment]
Perhaps this was just a mistake, @gaelj did you mean to license this wrapper less permissively than CodeMirror?

**Comment by gaelj** [comment]
Indeed, I'm not an expert concerning licences. I'll change it to MIT as requested.
